name: set working directory and deploy
on: workflow_call
jobs:
    deploy:
      runs-on: ubuntu-22.04
     
      steps:
       - name: Use the working directory
         run: cd ${{ github.workspace }}/testfolder
       - name: Deploy Code
         run: echo "Deploying...."
