name: set working directory and deploy
on: workflow_call
jobs:
    deploy:
      runs-on: ubuntu-22.04
      env:
       WORKING_DIRECTORY: ${{ github.workspace }}
      steps:
       - name: Set working directory
         run: echo "WORKING_DIRECTORY=${{ github.workspace }}" >> $GITHUB_ENV

       - name: Use the working directory
         run: cd $WORKING_DIRECTORY
       - name: Deploy Code
         run: echo "Deploying...."
